




app: ui.o iml1.o
	gcc ui.o iml.o -o app
	@echo "Application Created Succesfully"
ui.o:interface.c
	gcc -c interface.c -o ui.o
	@echo "ui.o generated"
iml1.o:iml.c
	gcc -c iml.c -o iml1.o
	@echo "iml1.o created"

